name: "{{ cookiecutter.project_slug }}-env"
channels:
  - conda-forge
dependencies:
  - python=3.14
  - pip
{%- if cookiecutter.use_geospatial == "y" %}
  - gdal
{%- endif %}
{%- if cookiecutter.use_iiif == "y" %}
  - libvips
{%- endif %}
  - pip:
    # Core configuration
    - -r requirements.txt
